export const HELP = {
  firstName: "Saisir le prénom tel qu'indiqué sur les pièces officielles",
  lastName: "Saisir le nom de famille",
  email: "Adresse email valide (ex: nom@domaine.tld)",
  phone: "Numéro de téléphone (format local ou international, ex: +33...)",
  address: "Adresse postale complète",
  gender: "Genre (Homme / Femme)",
  maritalStatus: "État civil (Célibataire / Marié)",
  childrenUnder18: "Nombre d'enfants de moins de 18 ans (entier, minimum 0)",
  socialSecurityNumber: "Numéro de Sécurité sociale (15 chiffres)",
  birthDate: "Date de naissance",
  hireDate: "Date d'embauche",
  endDate: "Date de fin de contrat (si applicable)",
  employeeNumber: "Laisser vide pour une génération automatique (ex: A-000123)",
  employeeNumberEdit: "Matricule unique de l'employé",
  contractType: "Type de contrat (CDI / CDD / CI)",
  status: "Statut de l'employé (ex: ACTIVE)",
  positionId: "Poste occupé (détermine la catégorie via le barème)",
  category: "Catégorie issue du barème du poste (lecture seule)",
};
